commit_conventions:
  types:
    - feat
    - fix
    - docs
    - style
    - refactor
    - test
    - chore
    - build
    - ci
    - perf
    - revert
  scope_required: true
  description_max_length: 72
  description_required: true
